server:
  port: 9192
spring:
  config:
    import: optional:configserver:http://localhost:9196
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: beans,env,health,info
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"



